# Gola Project Configuration
# Main configuration file for the Gola system

# Default settings
default_mode: general
router_policy: throughput  # conserve|throughput|audit
log_level: INFO
debug: false

# Data processing settings
max_file_size_mb: 100
supported_formats:
  - pdf
  - txt
  - docx
  - html
  - json
  - csv
  - md

# GPU monitoring
gpu_monitoring:
  enabled: true
  poll_interval_seconds: 2
  utilization_threshold: 85
  memory_threshold: 92
  cooldown_seconds: 10

# Quality gates
quality_gates:
  duplication_ratio_max: 0.10
  coverage_min: 0.85
  hallucination_max: 0.02
  evidence_span_coverage_min: 0.80

# Budget settings
budgets:
  daily_usd: 25
  max_tokens_per_request: 4096
  max_concurrent_requests: 10

# Providers configuration
providers:
  lmstudio:
    enabled: true
    base_url: http://127.0.0.1:1234/v1
    models:
      - local/llama-3-8b
      - local/gemma-2-9b
    max_tokens: 4096
    temperature: 0.2
    
  anthropic:
    enabled: true
    models:
      - claude-3.7-sonnet
      - claude-3.5-sonnet
    max_tokens: 4096
    temperature: 0.2
    batches: true
    
  gemini:
    enabled: true
    models:
      - gemini-1.5-pro
      - gemini-1.5-flash
    max_tokens: 8192
    temperature: 0.2
    
  deepseek:
    enabled: true
    models:
      - deepseek-chat
      - deepseek-coder
    max_tokens: 4096
    temperature: 0.2
    
  xai:
    enabled: true
    models:
      - grok-4
      - grok-4-latest
    max_tokens: 4096
    temperature: 0.2
    
  openai:
    enabled: false
    models:
      - gpt-4
      - gpt-3.5-turbo
    max_tokens: 4096
    temperature: 0.2

# Router policies
router_policies:
  conserve:
    description: "Local-first, minimal cloud usage"
    local_priority: 1.0
    cloud_fallback: false
    pii_strict: true
    
  throughput:
    description: "Balanced local and cloud usage"
    local_priority: 0.8
    cloud_fallback: true
    pii_strict: false
    
  audit:
    description: "Local-only, strict validation"
    local_priority: 1.0
    cloud_fallback: false
    pii_strict: true

# Vector database settings
vector_db:
  type: qdrant
  host: localhost
  port: 6333
  collection_prefix: gola_
  embedding_dimension: 768
  distance_metric: Cosine

# Database settings
database:
  type: sqlite  # sqlite or postgres
  path: ./data/gola.db
  # postgres settings (if using postgres)
  # host: localhost
  # port: 5432
  # name: ai_forge_db
  # user: ai_forge_user
  # password: your_secure_password

# Storage paths
paths:
  data: ./data
  raw: ./data/raw
  parsed: ./data/parsed
  notes: ./data/notes
  chunks: ./data/chunks
  outputs: ./data/outputs
  manifests: ./data/manifests
  indexes: ./indexes
  logs: ./logs
  temp: ./temp

# Export settings
exports:
  formats:
    - jsonl
    - csv
    - parquet
  compression: gzip
  include_metadata: true
  include_evidence_spans: true

# MCP server settings
mcp:
  enabled: true
  host: localhost
  port: 3323
  max_connections: 10
  timeout_seconds: 300

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: ./logs/gola.log
  max_size_mb: 100
  backup_count: 5 