/* perspective_dcide/libs/mui_v5/mui_loader.js
   Lazy-loads the tree-shaken Material-UI v5 bundle generated by lib_bundler.
   First call fetches the local blob (gzipped JS), injects CSS once, then caches.
*/
let muiPromise;

function getLocalBlobUrl(blobName) {
  // Resolves to /perspective_dcide/libs/mui_v5/dist/<blobName>
  const base = window.location.origin + '/perspective_dcide/libs/mui_v5/dist/';
  return base + blobName;
}

function injectCss(cssFile) {
  if (document.querySelector(`link[data-mui="${cssFile}"]`)) return;
  const link = document.createElement('link');
  link.rel = 'stylesheet';
  link.href = getLocalBlobUrl(cssFile);
  link.dataset.mui = cssFile;
  document.head.appendChild(link);
}

export function loadMuiV5() {
  if (muiPromise) return muiPromise;
  const blobUrl = getLocalBlobUrl('mui_v5.min.js');
  muiPromise = import(/* webpackIgnore: true */ blobUrl).then((mod) => {
    injectCss('mui_v5.css');
    return mod;
  });
  return muiPromise;
} 